algo: ppo
algo_config:
  # model args
  hidden_dim: 64
  activation: tanh
  norm_obs: False
  norm_reward: False
  clip_obs: 10.0
  clip_reward: 10.0

  # loss args
  gamma: 0.99
  use_gae: True
  gae_lambda: 0.95
  use_clipped_value: False
  clip_param: 0.2
  target_kl: 0.01
  entropy_coef: 0.01

  # optim args
  opt_epochs: 10
  mini_batch_size: 64
  actor_lr: 0.0003
  critic_lr: 0.001
  max_grad_norm: 0.5

  # runner args
  max_env_steps: 100000
  num_workers: 1
  rollout_batch_size: 4
  rollout_steps: 100
  deque_size: 10
  eval_batch_size: 10

  # misc
  log_interval: 1000
  save_interval: 1000
  num_checkpoints: 0
  eval_interval: 1000
  eval_save_best: True
  tensorboard: False
