algo: sac
algo_config:
  # model args
  hidden_dim: 256
  activation: relu
  use_entropy_tuning: False

  # optim args
  train_interval: 100
  train_batch_size: 64
  actor_lr: 0.001
  critic_lr: 0.001
  entropy_lr: 0.001

  # runner args
  max_env_steps: 100000
  warm_up_steps: 1000
  rollout_batch_size: 4
  num_workers: 1
  max_buffer_size: 1000000
  deque_size: 10
  eval_batch_size: 10

  # misc
  log_interval: 1000
  save_interval: 1000
  num_checkpoints: 100
  eval_interval: 1000
  eval_save_best: True
  tensorboard: True
